version: '2'

services:
  synergy:
    image: fabiorauber/synergy:1.9.1
    hostname: synergy
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1 
    volumes:
      - '~/.config/Synergy/Synergy.conf:/home/synergy/.config/Synergy/Synergy.conf'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    ports:
      - "24800:24800"
